### ISSUE TITLE
知乎回答api

### ISSUE THREAD

**Issue by tararata** [liuxukun2000/Zhihu_spider#1]
你好 我是python小白 我想问下知乎这个api接口打不开呀？
 https://www.zhihu.com/api/v4/questions/586488911//answers?include=content&limit=5&offset=10

**Comment by liuxukun2000** [comment]
你好，这个接口前几天被ban了。还有一个比较简单的方法是使用webdriver。

**Comment by tararata** [comment]
> 你好，这个接口前几天被ban了。还有一个比较简单的方法是使用webdriver。

哦哦哦，感谢回复！是用webdriver去打开浏览器，把一个问题下的所有答案加载出来再抓取是吗？我是这么写的，但加载页面一开始是正常的，到后面就异常慢😭 所以想着找接口来爬～但我不太会抓包找接口>< 所以知乎现在没有可以使用的提问和回答接口吗？

**Comment by liuxukun2000** [comment]
目前还是有的，如果要用API的话我可以把具体思路给你：
![image](https://user-images.githubusercontent.com/57486241/223741562-729fd914-ddd7-4f8b-84ae-88954bcde340.png)
这个包在这里，需要的是一个叫cursor的东西。下一次的cursor可以在响应里找到：
![image](https://user-images.githubusercontent.com/57486241/223741991-dd55d37d-1ebf-4bb5-8f52-929635e23d79.png)
